function [p, finishflag] = getpartition(fid, p)

% generate partition vector (binary vector picking out components) from
% dlink file generated by dancinglinks

% assume position indicator of FID is at start of the entries for a
% partition 

tline = fgetl(fid);
if tline(1)=='A' % starting new partition
  finishflag = 1;
  return;
else 
  b = textscan(tline, '%d');
  p(b{1}) = 1;
end
